#!/usr/bin/env python
# -*- coding: utf-8 -*-

import numpy as np
from scipy.signal import savgol_filter
from scipy.ndimage import gaussian_filter1d
import matplotlib.pyplot as plt
import matplotlib.animation as animation
import subprocess
import libwt
from argparse import ArgumentParser, ArgumentTypeError

DEFAULTS = {
    "num_waveforms": 256,
    "num_samples": 2048,
    "bitwidth": 32,
    "dpi": 200,
    "exponent": 5,
    "mid_width_pct": 60,
    "mid_yoffset": 25
}


def debug(msg):
    if args.debug:
        print(msg)


def exp_curve(x1, y1, x2, y2, num_points):
    debug(f'curve: {x1} {y1} {x2} {y2} {num_points}')
    x = np.linspace(x1, x2, num_points)
    y = y1 + (y2 - y1) * (np.exp(args.exp * (x - x1)) - 1) / \
        (np.exp(args.exp * (x2 - x1)) - 1)
    if x1 < 0:
        y_rotated = y2 - (y - y1)
        return y_rotated[::-1]

    return y


def bezier_curve(x1, y1, x2, y2, num_points):
    t_values = np.linspace(0.0, 1.0, num_points)
    # pre-allocate to improve performance
    x_values = np.zeros(num_points)
    y_values = np.zeros(num_points)
    x = np.where(x1 < 0, x1, x2)
    y = np.where(x1 < 0, y2, y1)

    for i, t in enumerate(t_values):
        x_values[i] = (1 - t)**2 * x1 + 2 * (1 - t) * t * x + t**2 * x2
        y_values[i] = (1 - t)**2 * y1 + 2 * (1 - t) * t * y + t**2 * y2

    return y_values


def line(x1, y1, x2, y2, num_points):
    debug(f'line: {x1} {y1} {x2} {y2} {num_points}')
    if x1 == x2:
        y_values = np.linspace(y1, y2, num_points)
    else:
        x_values = np.linspace(x1, x2, num_points)
        y_values = y1 + ((y2 - y1) / (x2 - x1)) * (x_values - x1)
    return y_values


def fmt_fn(ext):
    if ext == 'wav':
        fn = f'%dm_%dh_%s{suffix}' % (
                 args.mid_width_pct,
                 args.mid_yoffset,
                 mtype)
        if args.fullname:
            fn = f'{fn}_%ds_%dw' % (
                args.num_samples,
                args.num_waveforms)
    elif ext == 'wt':
        fn = f'%dm_%dh_%s{suffix}' % (
                 args.mid_width_pct,
                 args.mid_yoffset,
                 mtype)
        if args.fullname:
            fn = f'{fn}_%ds_%dw' % (
                args.num_samples,
                args.num_waveforms)
    elif ext == 'h2p':
        fn = f'%dm_%dh_%s{suffix}' % (
                 args.mid_width_pct,
                 args.mid_yoffset,
                 mtype)
        if args.fullname:
            fn = f'{fn}_%ds_%dw' % (
                args.num_samples,
                args.num_waveforms)
    elif ext == 'gif':
        fn = '%dm_%dh_%s' % (
                args.mid_width_pct,
                args.mid_yoffset,
                mtype)
        fn = f'{fn}{suffix}_anim'
    else:
        exit(1)
    return f'{fn}.{ext}'


def tuple_2int(value):
    try:
        items = [int(x) for x in value.split(',')]
        if len(items) != 2:
            raise ArgumentTypeError("Tuple argument must contain 2 items separated by comma")
        return tuple(items)
    except:
        raise ArgumentTypeError("Invalid tuple argument")

argp = ArgumentParser()
argp.add_argument(
    "-w", dest="num_waveforms", type=int,
    default=DEFAULTS['num_waveforms'],
    help="Number of waveforms (%(default)s)")
argp.add_argument(
    "-s", dest="num_samples", type=int,
    default=DEFAULTS['num_samples'],
    choices=np.power(2, np.arange(4, 13)),
    help="Number of samples in waveform (%(default)s)")
argp.add_argument(
    "--bits", dest="bitwidth", type=int,
    default=DEFAULTS['bitwidth'],
    choices=[16, 32],
    help="Bit width (%(default)s)")
argp.add_argument(
    "-m", dest="mid_width_pct", type=int,
    default=DEFAULTS['mid_width_pct'],
    help="Middle part width in %% (%(default)s)")
argp.add_argument(
    "-o", dest="mid_yoffset", type=int,
    default=DEFAULTS['mid_yoffset'],
    help="Offset from y-axis in %% (%(default)s)")
argp.add_argument(
    "-e", dest="exp", type=int,
    default=DEFAULTS['exponent'],
    choices=range(2, 10),
    help="Exponent of curve (%(default)s)")
argp.add_argument(
    "-B", action='store_true',
    dest="bezier", help="Build Bezier curve instead of exponent")
argp.add_argument(
    "-L", action='store_true',
    dest="direct", help="Direct line instead of curve")
argp.add_argument(
    "--savgol", dest="savgol", type=tuple_2int,
    help="Savitzky-Golay filter window_length_pct(1-100),polyorder, e.g. '51,3'")
argp.add_argument(
    "--gauss", dest="gauss", type=int,
    help="Gaussian filter, int sigma, e.g. 2")
argp.add_argument(
    "--graph", action='store_true',
    dest="graph", help="Plot graph")
argp.add_argument(
    "--wav", action='store_true', dest="wav", help="Save wav")
argp.add_argument(
    "--wt", action='store_true', dest="wt",
    help="Save wt (Bitwig/Surge)")
argp.add_argument(
    "--h2p", action='store_true', dest="h2p", help="Save Zebra OSC h2p")
argp.add_argument(
    "--gif", action='store_true', dest="gif", help="Save gif animation")
argp.add_argument(
    "--dpi", dest="dpi", type=int,
    help="Graph/gif DPI (%(default)s)",
    default=DEFAULTS['dpi'])
argp.add_argument(
    "-O", action='store_true', dest="open",
    help="Open gif")
argp.add_argument(
    "--fullfn", action='store_true', dest="fullname",
    help="Add full info to file name")
argp.add_argument(
    "-D", action='store_true', dest="debug", help="Debug")
args = argp.parse_args()

if not (args.wav or args.graph or args.debug or args.gif or
        args.h2p or args.wt):
    print(f'What to do?\n\n{argp.format_help()}')
    exit()

if args.bezier:
    curve_fn = bezier_curve
    title = 'Bézier curve'
    mtype = 'bz'
elif args.direct:
    curve_fn = line
    title = 'Direct line'
    mtype = 'dl'
else:
    curve_fn = exp_curve
    title = 'Exponential curve'
    mtype = f'{args.exp}e'
suffix=''
if args.savgol:
    title = f'{title} savgol={args.savgol}'
    suffix = f'{suffix}_sg{args.savgol[0]}-{args.savgol[1]}'
if args.gauss:
    title = f'{title} gauss={args.gauss}'
    suffix = f'{suffix}_ga{args.gauss}'

if args.h2p:
    args.num_samples = 128
    args.num_waveforms = 16

mid_samples = int((args.mid_width_pct / 100) * args.num_samples)
mid_samples -= mid_samples % 2
debug(f'mid_samples: {mid_samples} ({args.mid_width_pct}% of {args.num_samples})')

mid_widths = np.round(mid_samples * np.arange(args.num_waveforms) /
                      (args.num_waveforms - 1)).astype(int)
mid_widths -= mid_widths % 2
debug(f'mid_widths: {mid_widths}')

mid_yoffset = args.mid_yoffset * 0.01
# debug(f'mid_yoffset: {mid_yoffset}')

wf = np.zeros((args.num_waveforms, args.num_samples))
debug(f'wf shape: {wf.shape}')
xoffsets = np.linspace(0, args.mid_width_pct / 100, args.num_waveforms)

for i in range(args.num_waveforms):
    cx = xoffsets[i]
    debug(f'cx: {cx}')

    curve_len = args.num_samples // 2 - mid_widths[i] // 2
    debug(
        f'i: {i} curve_len: {curve_len}, mw: {mid_widths[i]}, '
        f'sum: {curve_len*2+mid_widths[i]}')

    ya1 = curve_fn(-1, -1, -cx, -mid_yoffset, curve_len)
    debug(f'ya1: {ya1} ({len(ya1)})')
    ya2 = curve_fn(cx, mid_yoffset, 1, 1, curve_len)
    debug(f'ya2: {ya2} ({len(ya2)})')
    ym = line(-cx, -mid_yoffset, cx, mid_yoffset, mid_widths[i])
    debug(f'ym: {ym} ({len(ym)})')
    y = np.concatenate((ya1, ym, ya2))
    debug(f'y: {y} {y.shape}')
    if args.savgol:
        if not args.savgol[0] in range(1,100):
            print('savgol window should be in range 1-100%')
            exit()
        wlen = int(args.num_samples / 100 * args.savgol[0])
        y = savgol_filter(y, window_length=wlen, polyorder=args.savgol[1])
    if args.gauss:
        # 2
        y = gaussian_filter1d(y, sigma=args.gauss)


    wf[i] = y

np.set_printoptions(linewidth=100, precision=2, suppress=True)

if args.debug:
    print(wf)
    exit()

if args.graph:
    plt.rcParams['figure.dpi'] = args.dpi
    x = np.linspace(0, 100, args.num_samples)
    plt.xticks(np.arange(min(x), max(x)+1, 25))
    plt.plot(x,wf[0], 'm-', label='first waveform')
    plt.plot(x,wf[-1], 'c-',  label='last waveform')
    plt.xlabel('Samples %')
    plt.ylabel('Amplitude')
    plt.title(
        f'{title} e={args.exp} m={args.mid_width_pct}% '
        f'h={args.mid_yoffset}% '
        f's={args.num_samples} w={args.num_waveforms}')
    plt.grid(True)
    plt.legend()
    plt.show()

if args.wav:
    fn = fmt_fn('wav')
    print(f'saving: {fn}')
    wt = libwt.Wt(wf, args.bitwidth)
    wt.save_wav(fn)

if args.wt:
    fn = fmt_fn('wt')
    print(f'saving: {fn}')
    wt = libwt.Wt(wf, args.bitwidth)
    wt.save_wt(fn)

if args.h2p:
    fn = fmt_fn('h2p')
    print(f'saving: {fn}')
    wt = libwt.Wt(wf)
    wt.save_h2p(fn)

if args.gif:
    pct1 = args.num_waveforms / 100
    fig, ax = plt.subplots()
    lines = []
    for pct in range(0, 100, 20):
        line, = ax.plot(wf[int(pct*pct1)], 'm-')
        lines.append([line])
    ax.set_xlabel('Samples')
    ax.set_ylabel('Amplitude')
    param = '' if args.bezier or args.direct else f'e={args.exp} '
    ax.set_title(
        f'{title} {param}m={args.mid_width_pct}% '
        f'h={args.mid_yoffset}%')
    ax.grid(True)
    anim = animation.ArtistAnimation(fig, lines, interval=500, blit=True)
    fn = fmt_fn('gif')
    print(f'saving: {fn}')
    anim.save(fn, writer='pillow', dpi=args.dpi)
    if args.open:
        try:
            cmd = f'mimeopen {fn}'
            result = subprocess.run(cmd, shell=True, capture_output=True, text=True)
        except subprocess.CalledProcessError as e:
            print(e.returncode, e.stdout, e.stderr)

